# .github/workflows/ci.yml
name: C++ CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Шаги для выполнения сборки и тестирования

    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Переход в папку OOP, где лежит CMakeLists.txt
    - name: Change to OOP directory
      run: cd lab1

    # Установка CMake
    - name: Install CMake
      run: sudo apt-get install cmake

    # Установка GCC
    - name: Install GCC
      run: sudo apt-get install g++

    # Установка GoogleTest
    - name: Install GoogleTest dependencies
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib

    # Сборка проекта
    - name: Build with CMake
      run: |
        cd OOP
        mkdir -p build
        cd build
        cmake ..
        make

    # Запуск тестов
    - name: Run tests
      run: |
        cd OOP/build
        ctest --output-on-failure
