# .github/workflows/ci.yml
name: C++ CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Шаги для выполнения сборки и тестирования

    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка CMake и других инструментов
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake g++ -y

    # Сборка проекта с использованием встроенного FetchContent для GoogleTest
    - name: Build with CMake
      run: |
        cd lab1
        mkdir -p build
        cd build
        cmake ..
        make

    # Запуск тестов
    - name: Run tests
      run: |
        cd lab1/build
        ctest --output-on-failure

    - name: Verify binary
      run: |
          ls -la lab1/build/bin

      # Шаг для загрузки артефактов сборки
    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: vowel_counter_binary
        path: lab1/build/bin/vowel_counter

  # Шаг для создания релиза после успешной сборки и тестирования
  release:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download binary
      uses: actions/download-artifact@v3
      with:
        name: vowel_counter_binary

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v1.1.4
        release_name: "Release v1.1.4"
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vowel_counter
        asset_name: vowel_counter
        tag: v1.1.4
    