# .github/workflows/ci.yml
name: C++ CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Шаги для выполнения сборки и тестирования

    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка CMake и других инструментов
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cmake g++ -y

    # Сборка проекта с использованием встроенного FetchContent для GoogleTest
    - name: Build with CMake
      run: |
        cd lab1
        mkdir -p build
        cd build
        cmake ..
        make

    # Запуск тестов
    - name: Run tests
      run: |
        cd OOP/build
        ctest --output-on-failure
