# .github/workflows/ci.yml
name: C++ CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Проверка кода из репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка CMake, g++, и всех необходимых библиотек
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          g++ \
          libsfml-dev \
          libx11-dev \
          libxrandr-dev \
          libxi-dev \
          libudev-dev \
          libopenal-dev \
          libvorbis-dev \
          libflac-dev \
          python3 \
          wget \
          git

    # Установка Emscripten
    - name: Install Emscripten
      run: |
        sudo git clone https://github.com/emscripten-core/emsdk.git /emsdk
        cd /emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "source /emsdk/emsdk_env.sh" >> ~/.bashrc
        source /emsdk/emsdk_env.sh

    # Установка Google Test
    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build
        cd build
        cmake ..
        make
        sudo make install

    # Сборка проекта lab1
    - name: Build lab1 with CMake
      run: |
        cd lab1
        mkdir -p build
        cd build
        cmake ..
        make
        cd ../

    # Сборка проекта lab2
    - name: Build lab2 with CMake
      run: |
        cd lab2
        mkdir -p build
        cd build
        cmake ..
        make
        cd ../

    # Сборка проекта lab3
    - name: Build lab3 with CMake
      run: |
        cd lab3
        mkdir -p build
        cd build
        cmake ..
        make
        cd ../

    # Сборка проекта lab4
    - name: Build lab4 with CMake
      run: |
        cd lab4
        mkdir -p build
        cd build
        cmake ..
        make
        cd ../
    
    # Сборка проекта lab5
    - name: Build lab5 with CMake
      run: |
        cd lab5
        mkdir -p build
        cd build
        source /emsdk/emsdk_env.sh
        cmake ..
        make
        cd ../

    # Запуск тестов lab1
    - name: Run tests lab1
      run: |
        cd lab1/build
        ctest --output-on-failure
        cd ../

    # Запуск тестов lab2
    - name: Run tests lab2
      run: |
        cd lab2/build
        ctest --output-on-failure
        cd ../

    # Запуск тестов lab3
    - name: Run tests lab3
      run: |
        cd lab3/build
        ctest --output-on-failure
        cd ../

    # Запуск тестов lab4
    - name: Run tests lab4
      run: |
        cd lab4/build
        ctest --output-on-failure
        cd ../

    # Запуск тестов lab5
    - name: Run tests lab5
      run: |
        cd lab5/build
        ctest --output-on-failure
        cd ../

    # Верификация бинарных файлов
    - name: Verify binaries
      run: |
        ls -la lab1/build/bin
        ls -la lab2/build/bin
        ls -la lab3/build/bin
        ls -la lab4/build/bin
        ls -la lab5/build/bin

    # Шаги для загрузки артефактов сборки
    - name: Upload binary lab1
      uses: actions/upload-artifact@v3
      with:
        name: vowel_counter_binary
        path: lab1/build/bin/vowel_counter

    - name: Upload binary lab2
      uses: actions/upload-artifact@v3
      with:
        name: twelve_lab_binary
        path: lab2/build/bin/TwelveLab

    - name: Upload binary lab3
      uses: actions/upload-artifact@v3
      with:
        name: figures_lab_binary
        path: lab3/build/bin/Figures

    - name: Upload binary lab4
      uses: actions/upload-artifact@v3
      with:
        name: templates_lab_binary
        path: lab4/build/bin/Templates

    - name: Upload binary lab5
      uses: actions/upload-artifact@v3
      with:
        name: lab5_binary
        path: lab5/build/bin/Allocators

  release:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download binary lab1
      uses: actions/download-artifact@v3
      with:
        name: vowel_counter_binary

    - name: Download binary lab2
      uses: actions/download-artifact@v3
      with:
        name: twelve_lab_binary

    - name: Download binary lab3
      uses: actions/download-artifact@v3
      with:
        name: figures_lab_binary

    - name: Download binary lab4
      uses: actions/download-artifact@v3
      with:
        name: templates_lab_binary

    - name: Download binary lab5
      uses: actions/download-artifact@v3
      with:
        name: allocators_lab_binary

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v5.0.0
        release_name: "Release v5.0.0"
        draft: false
        prerelease: false

    - name: Upload Release Asset lab1
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: vowel_counter
        asset_name: vowel_counter
        tag: v5.0.0

    - name: Upload Release Asset lab2
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: TwelveLab
        asset_name: twelve_lab
        tag: v5.0.0

    - name: Upload Release Asset lab3
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Figures
        asset_name: figures
        tag: v5.0.0

    - name: Upload Release Asset lab4
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Templates
        asset_name: templates
        tag: v5.0.0

    - name: Upload Release Asset lab5
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: Allocators
        asset_name: allocators
        tag: v5.0.0

